name: Run tests for pull requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with: bun-version 1.0.8
      - name: Use cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/bun.lockb') }}
      - name: Install dependencies
        run: bun install --production --frozen-lockfile
      - name: Run tests
        run: bun run test
