name: Run tests for pull requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.8
      - name: Install dependencies
        run: bun install --production --frozen-lockfile
      - name: Run tests
        run: bun run test
